### PR TITLE
Read_me 

### PR DESCRIPTION
**Pull request by uh5331tc**
testing adding screen shots to the read_me document

### CODE REVIEW

**Review by Stewtec612 — COMMENTED** [review]
We changed the search by birthdate to search by zodiac sign

**Review by FireL0ki — COMMENTED** [review]
Are the readme_images so we have errors to share and talk about during the presentation?

**Review by FireL0ki — CHANGES_REQUESTED** [review]
App is still running on my end.

I can't see how to comment on a specific line in the readme file, but let's change 'spirit animal' to power animal before merging.

**Comment by uh5331tc** [comment]
> Are the readme_images so we have errors to share and talk about during the presentation?

yes

**Review by FireL0ki — APPROVED** [review]

**Comment by FireL0ki** [comment]
Everything is functioning for me, I see the full lists of requirements, and the instructions look good.

**Pull request merged**
